project_id = "cowcbkdmwcwblcpgxsgg"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.invite]
subject = "Einladung zu {{ .SiteURL }}"

[auth.email.template.confirmation]
subject = "Bestätigen Sie Ihre E-Mail-Adresse für {{ .SiteURL }}"

[auth.email.template.recovery]
subject = "Passwort zurücksetzen für {{ .SiteURL }}"

[auth.email.template.email_change]
subject = "E-Mail-Adresse ändern für {{ .SiteURL }}"

[functions.demo-management]
verify_jwt = true

[functions.import-members]
verify_jwt = true
